#-------------------------------------------------------------------------------------------------------------
#---------------- Master file for Content Manager server installation        --------------------------------- 
#-------------------------------------------------------------------------------------------------------------
- hosts: localhost
  connection: local
  become: true
  vars:
    - component_type: "CM"
    - inst_user: "cog117cm"
    - super_user: "root"
    - env: "dev"
    - s3_bucket: "s3://creport-{{ env }}-s3-mgt/last"
  #Temporary variables
    - DBPORT: 23000
    - DB_URI: "creportdev.cit9nbofg1l2.eu-west-1.rds.amazonaws.com:23000"
    - DB_USER: "creport"
    - DB_PWD: "GsoHnXHnvbSFcKKrcoit"

  tasks:
    # Install base packages
    - include_tasks: tasks/packages/install_prerequired_package.yml
    
    #
    - include_tasks: tasks/users/create_user.yml
      vars:
        username: "{{ inst_user }}"
    
    #
    - include_tasks: tasks/ec2_setup/set_ulimits.yml
      vars:
        - user: "{{ super_user}}"
        - nofile_limit_for: "{{ inst_user }}"
    
    #
    - include_tasks: tasks/installation/install_binaries_CM.yml
      vars:
        - root_folder: "/opt"
        - app_folder: "{{ root_folder }}/appl"
        - sources_folder: "{{ app_folder }}/sources"
        - drivers_folder: "{{ app_folder }}/{{ inst_user }}/drivers"
        - configuration_folder: "{{ app_folder }}/{{ inst_user }}/configuration"
        - s3_bucket_with_sources: "{{ s3_bucket }}/cognos"
        - s3_bucket_configuration_files: "{{ s3_bucket_with_sources }}/ConfigFiles"

    - name: Start CM server
      shell: "/opt/appl/{{ inst_user }}/bin64/cogconfig.sh -s"
      become_user: "{{ inst_user }}"
