#-------------------------------------------------------------------------------------------------------------
#----------------   Master file for Gateway server installation              --------------------------------- 
#-------------------------------------------------------------------------------------------------------------
- hosts: localhost
  connection: local
  become: true
  vars:
    - component_type: "GW"
    - inst_user: "cog117gw"
    - super_user: "root"
    - env: "dev"
    - s3_bucket: "s3://creport-{{ env }}-s3-mgt"
  tasks:   
    # Install base packages
    - include_tasks: tasks/packages/install_prerequired_package.yml
    
    #
    - include_tasks: tasks/users/create_user.yml
      vars:
        username: "{{ inst_user }}"
    
    #
    - include_tasks: tasks/ec2_setup/set_ulimits.yml
      vars:
        - user: "{{ super_user}}"
        - nofile_limit_for: "{{ inst_user }}"
    
    - include_tasks: tasks/installation/install_apache.yml

    #
    - include_tasks: tasks/installation/install_binaries_GW.yml
      vars:
        - root_folder: "/opt"
        - app_folder: "{{ root_folder }}/appl"
        - sources_folder: "{{ app_folder }}/sources"
        - drivers_folder: "{{ app_folder }}/{{ inst_user }}/drivers"
        - configuration_folder: "{{ app_folder }}/{{ inst_user }}/configuration"
        - images_folder: "{{ app_folder }}/{{ inst_user }}/webcontent/bi/samples/images/" 
        - s3_bucket_with_sources: "{{ s3_bucket }}/cognos"
        - s3_bucket_configuration_files: "{{ s3_bucket_with_sources }}/ConfigFiles"
