#-----------------------------------------------------------------------------------------
#-----------                 Include for Apache installation             -----------------
#-----------------------------------------------------------------------------------------

- name: Install the latest version of Apache
  ansible.builtin.dnf:
    name: httpd
    state: latest

- name: Generate cognos.conf from template
  include_tasks: tasks/installation/apply_template.yml
  vars:
    - hostname_as1: "{{ PrimaryAnalytic }}" 
    - hostname_as2: "{{ SecondaryAnalytic }}" 
    - dispatcher_port: 9300
    - template: "../templates/config/cognos.conf.j2"
    - file_dst: "/etc/httpd/conf.d/cognos.conf"
    - owner: "{{ inst_user }}"
    - mode: 0655


- name: Enable service httpd
  ansible.builtin.service:
    name: httpd
    enabled: yes

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: started