- name: Create {{ username }} user
  user:
    name: "{{ username }}" 
    system: no 

- name: copy sudoers_{{ username }}
  copy:
    content: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/{{ username }}
    owner: root
    group: root
    mode: 0440
